name: Deploy to AWS Lambda from git repo

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Package Lambda function
      run: |
        zip lambda_function.zip lambda_function.py
 # Adjust this line to include all necessary files

    # - name: Upload to S3
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: 'us-east-1' 
    #     S3_BUCKET: 'lambda-code-repo-new-woodcock'  
    #     S3_KEY: 'lambda-code-repo-new-woodcock/lambda_fuction.zip'  
    #   run: |
    #     aws s3 cp lambda_function.zip s3://$S3_BUCKET/$S3_KEY

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  
        LAMBDA_FUNCTION_NAME: 'update_visitor_count'
        # S3_BUCKET: 'lambda-code-touching-koi'  
        # S3_KEY: 'lambda-code-touching-koi/lambda_fuction.zip'  
      run: |
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda_function.zip
